### ISSUE TITLE
Sette opp MongoDB til NodeBB i GCP

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-community-store#2]
1. High Availablity
2. Backup/restore
3. Initial setup

**Comment by valosnah** [comment]
Mongodb satt opp i alle tre miljø. Backup tas (på linje med alle andre disker) en gang i døgnet, rundt midnatt. Kan øke frekvensen på dette (inntil én gang i timen) hvis vi synes det er behov
